[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "MCP server that connects to Max AI agents"
readme = "README.md"
requires-python = ">=3.10.7"
dependencies = [
    "fastmcp>=2.10.0",
    "answerrocket-client>=0.2.59",
    "mcp[cli]>=1.10.1",
]

[tool.setuptools]
packages = ["server"]

[tool.uv.sources]
answerrocket-client = { git = "ssh://git@github.com/answerrocket/answerrocket-python-client.git", rev = "get-copilots-for-mcp" }

